stages:
  load_data:
    cmd: python src/load_raw_data.py --config=params.yaml
    deps:
    - src/load_raw_data.py
    - src/get_data.py
    - data_source/winequality.csv
    outs:
    - data/raw/winequality.csv
  split_data:
    cmd: python src/process_raw_data.py --config=params.yaml
    deps:
    - src/process_raw_data.py
    - src/get_data.py
    - data/raw/winequality.csv
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv
  train_and_evaluate_models:
    cmd: python src/train_and_evaluate_models.py --config=params.yaml
    deps:
    - src/train_and_evaluate_models.py
    - src/get_data.py
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv
    outs:
    - models/model.joblib
    metrics:
    - report/params.json:
        cache: false
    - report/scores.json:
        cache: false
    params:
    - training_models.ElasticNet.params.l1_ratio
    - training_models.ElasticNet.params.alpha
